version: '3.8'

services:
  # Conteneur pour PostgreSQL
  database:
    image: 'postgres:15.2'
    ports:
      - '15432:5432'
    environment:
      - 'POSTGRES_USER=hoyoux'
      - 'POSTGRES_DB=rifletDB'
      - 'POSTGRES_PASSWORD=password'

  # Conteneur pour le frontend (Vue.js)
  frontend:
    build:
      context: ../frontend
    ports:
      - '3000:8080'  # Mapper le port 8080 du serveur Vue.js sur le port local 3000
    volumes:
      - ../frontend:/app  # Monter le répertoire local ./frontend dans /app du conteneur
      - /app/node_modules  # Éviter que node_modules soit écrasé par le volume monté
    environment:
      - CHOKIDAR_USEPOLLING=true  # Utiliser le polling pour le hot reload sur Docker
